<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="waking_robot">

    <xacro:property name="PI" value="3.1415926535897931" />
    <material name="matte_deep_grey"><color rgba="0.15 0.15 0.15 1.0"/></material>
    <material name="metallic_silver"><color rgba="0.75 0.75 0.75 1.0"/></material>
    <material name="vibrant_orange"><color rgba="1.0 0.45 0.0 1.0"/></material>
    <material name="smoky_black"><color rgba="0.05 0.05 0.05 1.0"/></material>

    <xacro:property name="base_width" value="0.27" />
    <xacro:property name="base_depth" value="0.16" />
    <xacro:property name="base_height" value="0.1" />
    <xacro:property name="wheel_radius" value="0.06" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="arm_base_length" value="0.04" />
    <xacro:property name="big_arm_length" value="0.20" />
    <xacro:property name="small_arm_length" value="0.18" />
    <xacro:property name="camera_link_size" value="0.05" />

    <xacro:property name="base_mass" value="25.0" />
    <xacro:property name="base_com_z" value="0.01" />
    
    <xacro:property name="arm_mass_scale" value="0.5" /> 
    <xacro:property name="camera_mass" value="0.01" />

    <xacro:property name="joint_damping" value="0.5" />
    <xacro:property name="joint_friction" value="0.1" />

    <xacro:property name="wheel_mass" value="1.5" />
    <xacro:property name="wheel_friction" value="0.0" />

    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(1.0/12.0)*m*(h*h + d*d)}" ixy="0.0" ixz="0.0"
                     iyy="${(1.0/12.0)*m*(w*w + d*d)}" iyz="0.0"
                     izz="${(1.0/12.0)*m*(w*w + h*h)}"/>
        </inertial>
    </xacro:macro>
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(1.0/12.0)*m*(3.0*r*r + h*h)}" ixy="0.0" ixz="0.0"
                     iyy="${(1.0/12.0)*m*(3.0*r*r + h*h)}" iyz="0.0"
                     izz="${0.5*m*r*r}"/>
        </inertial>
    </xacro:macro>

    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    <link name="base_link">
        <visual>
            <geometry><box size="${base_width} ${base_depth} ${base_height}"/></geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <material name="matte_deep_grey"/>
        </visual>
        <collision>
            <geometry><box size="${base_width} ${base_depth} ${base_height}"/></geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="${base_mass}"/>
            <origin xyz="0 0 ${base_com_z}" rpy="0 0 0"/>
            <inertia ixx="${(1.0/12.0)*base_mass*(base_depth*base_depth + base_height*base_height)}"
                     ixy="0.0" ixz="0.0"
                     iyy="${(1.0/12.0)*base_mass*(base_width*base_width + base_height*base_height)}"
                     iyz="0.0"
                     izz="${(1.0/12.0)*base_mass*(base_width*base_width + base_depth*base_depth)}"/>
        </inertial>
    </link>

    <xacro:macro name="create_wheel" params="prefix y_pos x_pos rpy_rot hubcap_y">
        <joint name="base_to_${prefix}_wheel" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${x_pos} ${y_pos} 0"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="0.0" friction="0.0"/> </joint>
        <link name="${prefix}_wheel">
            <visual>
                <origin rpy="${rpy_rot} 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
                <material name="matte_deep_grey"/>
            </visual>
            <visual name="hubcap">
                <origin rpy="${rpy_rot} 0 0" xyz="0 ${hubcap_y} 0"/>
                <geometry><cylinder radius="${wheel_radius*0.4}" length="0.002"/></geometry>
                <material name="vibrant_orange"/>
            </visual>
            <collision>
                <origin rpy="${rpy_rot} 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_length}"/></geometry>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>
        <transmission name="${prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="base_to_${prefix}_wheel">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_wheel_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:create_wheel prefix="front_left" y_pos="${base_depth/2.0}" x_pos="${base_width/4.0}" rpy_rot="${PI/2.0}" hubcap_y="${wheel_length/2.0 + 0.001}"/>
    <xacro:create_wheel prefix="rear_left" y_pos="${base_depth/2.0}" x_pos="${-base_width/4.0}" rpy_rot="${PI/2.0}" hubcap_y="${wheel_length/2.0 + 0.001}"/>
    <xacro:create_wheel prefix="front_right" y_pos="${-base_depth/2.0}" x_pos="${base_width/4.0}" rpy_rot="${-PI/2.0}" hubcap_y="${-wheel_length/2.0 - 0.001}"/>
    <xacro:create_wheel prefix="rear_right" y_pos="${-base_depth/2.0}" x_pos="${-base_width/4.0}" rpy_rot="${-PI/2.0}" hubcap_y="${-wheel_length/2.0 - 0.001}"/>

    <joint name="arm_base_joint" type="revolute">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.57" upper="1.57" effort="20.0" velocity="2.0"/>
        <dynamics damping="${joint_damping}" friction="${joint_friction}"/> 
    </joint>
    <link name="arm_base_link">
        <visual>
            <geometry><cylinder radius="0.04" length="${arm_base_length}"/></geometry>
            <origin xyz="0 0 ${arm_base_length/2.0}" rpy="0 0 0"/>
            <material name="metallic_silver"/>
        </visual>
        <collision>
            <geometry><cylinder radius="0.04" length="${arm_base_length}"/></geometry>
            <origin xyz="0 0 ${arm_base_length/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="${0.5*arm_mass_scale}" r="0.04" h="${arm_base_length}"/>
    </link>
    <transmission name="arm_base_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="arm_base_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="arm_base_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction> 
        </actuator>
    </transmission>

    <joint name="big_arm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="big_arm_link"/>
        <origin xyz="0 0 ${arm_base_length}" rpy="0 -2.3 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-1.5" upper="1.5" effort="20.0" velocity="2.0"/>
        <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>
    <link name="big_arm_link">
        <visual>
            <geometry><box size="${big_arm_length} 0.04 0.04"/></geometry>
            <origin xyz="${big_arm_length/2.0} 0 0" rpy="0 0 0"/>
            <material name="metallic_silver"/>
        </visual>
        <collision>
            <geometry><box size="${big_arm_length} 0.04 0.04"/></geometry>
            <origin xyz="${big_arm_length/2.0} 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="${1.0*arm_mass_scale}" w="${big_arm_length}" h="0.04" d="0.04"/>
    </link>
    <transmission name="big_arm_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="big_arm_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="big_arm_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <joint name="small_arm_joint" type="revolute">
        <parent link="big_arm_link"/>
        <child link="small_arm_link"/>
        <origin xyz="${big_arm_length} 0 0" rpy="0 2.4 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-1.5" upper="1.5" effort="20.0" velocity="2.0"/>
        <dynamics damping="${joint_damping}" friction="${joint_friction}"/>
    </joint>
    <link name="small_arm_link">
        <visual>
            <geometry><box size="${small_arm_length} 0.04 0.04"/></geometry>
            <origin xyz="${small_arm_length/2.0} 0 0" rpy="0 0 0"/>
            <material name="metallic_silver"/>
        </visual>
        <collision>
            <geometry><box size="${small_arm_length} 0.04 0.04"/></geometry>
            <origin xyz="${small_arm_length/2.0} 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="${0.8*arm_mass_scale}" w="${small_arm_length}" h="0.04" d="0.04"/>
    </link>
    <transmission name="small_arm_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="small_arm_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="small_arm_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <joint name="camera_joint" type="fixed">
        <parent link="small_arm_link"/>
        <child link="camera_link"/>
        <origin xyz="${small_arm_length} 0 0" rpy="0 0 0"/>
    </joint>
    <link name="camera_link">
        <visual>
            <geometry><box size="${camera_link_size} ${camera_link_size} ${camera_link_size}"/></geometry>
            <material name="vibrant_orange"/>
        </visual>
        <collision>
            <geometry><box size="${camera_link_size} ${camera_link_size} ${camera_link_size}"/></geometry>
        </collision>
        <xacro:box_inertia m="${camera_mass}" w="${camera_link_size}" h="${camera_link_size}" d="${camera_link_size}"/>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.1 0 ${base_height}" rpy="0 0 0"/>
    </joint>
    <link name="laser_frame">
        <visual>
            <geometry><cylinder radius="0.03" length="0.05"/></geometry>
            <material name="smoky_black"/>
        </visual>
        <collision>
            <geometry><cylinder radius="0.03" length="0.05"/></geometry>
        </collision>
        <xacro:cylinder_inertia m="0.05" r="0.03" h="0.05"/>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    </joint>
    <link name="imu_link">
        <visual>
            <geometry><box size="0.02 0.02 0.02"/></geometry>
            <material name="vibrant_orange"/>
        </visual>
        <collision>
            <geometry><box size="0.02 0.02 0.02"/></geometry>
        </collision>
        <xacro:box_inertia m="0.001" w="0.02" h="0.02" d="0.02"/>
    </link>

    <gazebo reference="base_link"><material>Gazebo/DarkGrey</material></gazebo>
    <gazebo reference="front_left_wheel"><material>Gazebo/DarkGrey</material></gazebo>
    <gazebo reference="front_right_wheel"><material>Gazebo/DarkGrey</material></gazebo>
    <gazebo reference="rear_left_wheel"><material>Gazebo/DarkGrey</material></gazebo>
    <gazebo reference="rear_right_wheel"><material>Gazebo/DarkGrey</material></gazebo>
    <gazebo reference="arm_base_link"><material>Gazebo/Silver</material></gazebo>
    <gazebo reference="big_arm_link"><material>Gazebo/Silver</material></gazebo>
    <gazebo reference="small_arm_link"><material>Gazebo/Silver</material></gazebo>
    <gazebo reference="camera_link"><material>Gazebo/Orange</material></gazebo>
    <gazebo reference="laser_frame"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="imu_link"><material>Gazebo/Orange</material></gazebo>

    <gazebo>
        <physics name="default_physics" default="true" type="ode">
            <max_step_size>0.001</max_step_size> <real_time_factor>1.0</real_time_factor>
            <real_time_update_rate>1000</real_time_update_rate>
            <ode>
                <solver>
                    <type>quick</type>
                    <iters>50</iters>
                    <sor>1.3</sor>
                </solver>
                <constraints>
                    <cfm>0.0</cfm>
                    <erp>0.2</erp>
                    <contact_max_correcting_vel>100.0</contact_max_correcting_vel>
                    <contact_surface_layer>0.001</contact_surface_layer>
                </constraints>
            </ode>
        </physics>
    </gazebo>

    <gazebo reference="front_left_wheel">
        <mu1>${wheel_friction}</mu1><mu2>${wheel_friction}</mu2>
    </gazebo>
    <gazebo reference="front_right_wheel">
        <mu1>${wheel_friction}</mu1><mu2>${wheel_friction}</mu2>
    </gazebo>
    <gazebo reference="rear_left_wheel">
        <mu1>${wheel_friction}</mu1><mu2>${wheel_friction}</mu2>
    </gazebo>
    <gazebo reference="rear_right_wheel">
        <mu1>${wheel_friction}</mu1><mu2>${wheel_friction}</mu2>
    </gazebo>

    <gazebo>
        <plugin name="planar_move_plugin" filename="libgazebo_ros_planar_move.so">
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryRate>50.0</odometryRate>
            <robotBaseFrame>base_footprint</robotBaseFrame>
            <publishOdometryTf>true</publishOdometryTf>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

    <gazebo reference="laser_frame">
        <sensor type="ray" name="laser_sensor">
            <visualize>false</visualize>
            <update_rate>10.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>${-PI}</min_angle>
                        <max_angle>${PI}</max_angle>
                    </horizontal>
                </scan>
                <range><min>0.1</min><max>10.0</max></range>
            </ray>
            <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser_frame</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo reference="camera_link">
        <sensor type="depth" name="camera_sensor">
            <update_rate>20.0</update_rate>
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image><width>640</width><height>480</height><format>R8G8B8</format></image>
                <clip><near>0.05</near><far>8.0</far></clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <cameraName>camera</cameraName>
                <alwaysOn>true</alwaysOn>
                <updateRate>20.0</updateRate>
                <imageTopicName>rgb/image_raw</imageTopicName>
                <depthImageTopicName>depth/image_raw</depthImageTopicName>
                <pointCloudTopicName>depth/points</pointCloudTopicName>
                <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
                <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
                <frameName>camera_link</frameName>
                <baseline>0.1</baseline>
            </plugin>
        </sensor>
    </gazebo>

    <gazebo reference="imu_link">
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100.0</update_rate>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>imu</topicName>
                <bodyName>imu_link</bodyName>
                <frameName>imu_link</frameName>
                <updateRateHZ>100.0</updateRateHZ>
            </plugin>
        </sensor>
    </gazebo>

</robot>